### ISSUE TITLE
Server Onload-Startup

### ISSUE THREAD

**Issue by ForgivenNin** [grimgravy/USBWebServer#2]
As far as I can see, `usbwebserver.exe` is the only or main file that boots up everything when the program is loaded by the flash drive. Could you please go into detail and explain how this works (including any other files that have a role in this process)?

_I tried looking at the code on Atom, but to my memory it wasn't very understandable to me._

**Comment by grimgravy** [comment]
I'll leave a link for you to see [Portal USB](https://www.youtube.com/watch?v=lcJRKEK513U)

**Comment by ForgivenNin** [comment]
Thanks. So I'm guessing this is somebody else's?
