### ISSUE TITLE
run time error 13

### ISSUE THREAD

**Issue by tri1976** [grimgravy/USBWebServer#3]
The executable usbwebserver.exe threw an error
Run time error 13
Type mismatch

Can you please look into what's causing the error?

Thanks.

**Comment by grimgravy** [comment]
[Download Microsoft c++ 2015 (32bits)](https://www.microsoft.com/pt-br/download/details.aspx?id=48145)
[Download Microsoft c++ 2013 (32bits)](https://www.microsoft.com/en-us/download/details.aspx?id=40784)
